### PR TITLE
Index key now contains index type

### PR DESCRIPTION
**Pull request by Aloren**
It is possible to create index for the same bin, but with different type; such indexes will prevent QueryIndex from loading indexes cache.

### CODE REVIEW

**Comment by BrianNichols** [comment]
We will integrate these changes in the next java client release.

**Comment by BrianNichols** [comment]
This pull request conflicts with a previous pull request (https://github.com/aerospike/aerospike-client-java/pull/152).  Can you resolve the conflicts with the previous pull request and resubmit?

**Comment by Aloren** [comment]
@BrianNichols Not sure how do you expect me to resolve the conflicts if none of the branches is merged? It would be much simpler to rebase the second pull request to the master if any of the pull requests gets merged.

**Comment by BrianNichols** [comment]
This repo has been updated with the previous merged pull request (https://github.com/aerospike/aerospike-client-java/pull/152).   You can now modify this pull request to fix the merge conflicts.

**Comment by Aloren** [comment]
@BrianNichols I've updated the branch, thank you

**Comment by BrianNichols** [comment]
This pull request has been accepted.

**Comment by BrianNichols** [comment]
reactor-client tests are failing.  Not sure which pull request caused the failure, but this needs to be fixed before java client release.

**Comment by BrianNichols** [comment]
The reactor-client unit tests are still failing on my multi-node cluster.  I looked at the incremental source code changes and nothing of significance has changed, so I'm not surprised.

Note that the same reactor-client unit tests work fine on a single-node cluster .  Try running the reactor-client unit tests on a 2 node cluster.

**Comment by Aloren** [comment]
@kptfh please take a look

**Pull request closed without merging**
