### PR TITLE
add retry functionality for reactor client

### PR DESCRIPTION
**Pull request by kptfh**
should fix https://github.com/aerospike/aerospike-client-java/issues/136 for reactor client

### CODE REVIEW

**Comment by kptfh** [comment]
Hi @BrianNichols 
We critically depend on this pull request. We can't go to production with reactor client without it.

**Comment by BrianNichols** [comment]
Your pull request has been accepted, but we are not in a position to release the java client this week.  We can discuss a reactor-client only release next week if absolutely necessary.

Also, we have decided to eventually move all extensions to a separate repository in the near future. This new repo will be managed similar to the existing spring-data-aerospike.

**Comment by tdanylchuk** [comment]
Hello, do we have any ETA on having release version with this change? 
Much appreciate for any info.

**Comment by BrianNichols** [comment]
I will try to perform an extensions only release on Friday.  The client itself is not ready to be released.

**Comment by BrianNichols** [comment]
Version 4.4.9.1 of aerospike-query-engine, aerospike-reactor-client and aerospike-reactor-query-engine libraries have been released to maven central (not on our website).

These libraries reference version 4.4.9 of aerospike-client.

**Comment by kptfh** [comment]
Hi @BrianNichols. Can't find any artifacts with 4.4.9.1 version here
[maven](https://mvnrepository.com/artifact/com.aerospike/aerospike-client)

**Pull request closed without merging**
