### PR TITLE
add failure cases to tests

### PR DESCRIPTION
**Pull request by kptfh**

### CODE REVIEW

**Comment by vasilievip** [comment]
any retry tests?

**Comment by kptfh** [comment]
No. Can't test retries without RetryListener.

**Comment by BrianNichols** [comment]
This pull request has been accepted.

**Comment by Aloren** [comment]
@kptfh maybe we could check timing of the whole operation that is tested? If it was retried -- timing of the whole operation will be increased compared to the one that did not have retries. What do you think?

**Comment by vasilievip** [comment]
This is not reliable

**Pull request closed without merging**
