### PR TITLE
Enhance query engine tests

### PR DESCRIPTION
**Pull request by Aloren**
use standard assertj assertions to simplify the tests logic

### CODE REVIEW

**Comment by BrianNichols** [comment]
This will appear in the next java client release as well.

**Comment by BrianNichols** [comment]
I have updated this repo with all previous merged pull requests.  This pull request now also has merge conflicts.

**Comment by Aloren** [comment]
Could you please firstly merge https://github.com/aerospike/aerospike-client-java/pull/154 ? So that I could resolve all conflicts at once.

**Comment by BrianNichols** [comment]
I did merge #154 into our private repo and updated this public repo yesterday.  See public repo commit:  https://github.com/aerospike/aerospike-client-java/commit/22ff2f3900382d7b03b04f4c48cabffca08a5e37

Github doesn't show the pull request as merged, but the commit is already there.

**Comment by BrianNichols** [comment]
Conflicts still exist.  Closing pull request.

**Pull request closed without merging**
